Repository nguyenleminhquan/bk-delivery-system, pull requests merged in 2023-06, with the labels that each got.

#91 BDS-53 Get vehicle by status (exported or not)
  backend/README.md
  backend/controllers/vehicleController.js
  backend/models/Vehicle.js
  backend/routes/vehicleRoutes.js
Labels: Feature

#95 BDS-63 Filter vehicle by route
  backend/README.md
  backend/controllers/vehicleController.js
  backend/routes/vehicleRoutes.js
Labels: Feature

#96 BDS-54 Export order on vehicle
  backend/README.md
  backend/controllers/vehicleController.js
  backend/models/ExportInfo.js
  backend/routes/vehicleRoutes.js
Labels: Feature

#97 feature: Create select option re-use component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AddressForm/index.js
  frontend/src/components/SelectOption/index.js
  frontend/src/pages/CreateOrder/CreateOrder.module.scss
  frontend/src/pages/CreateOrder/index.js
  frontend/src/styles/_variabless.scss
  frontend/src/styles/styles.scss
  frontend/src/utils/constants.js
Labels: Improve UI, Feature

#92 Feature: add api get-vehicle-by-region
  frontend/src/features/delivery/deliverySlice.js
  frontend/src/features/delivery/deliveryThunk.js
  frontend/src/pages/ExportOrder/index.js
  frontend/src/services/delivery.service.js
Labels: Improve Logic

#94 [Admin] Add field area_code when created a new employee
  frontend/src/components/GeneralConfirm/index.js
  frontend/src/features/user/userSlice.js
  frontend/src/pages/Roles/Admin/AdminEmployeeManagement/index.js
  frontend/src/utils/constants.js
  frontend/src/utils/consts/Delivery.const.js
  frontend/src/utils/consts/index.js
  frontend/src/utils/enums/index.js
  frontend/src/utils/enums/toast.enum.js
  frontend/src/utils/enums/user.num.js
Labels: Bug

#93 [Create Order] Update business of product section
  frontend/src/pages/CreateOrder/CreateOrder.module.scss
  frontend/src/pages/CreateOrder/index.js
  frontend/src/utils/consts/index.js
  frontend/src/utils/consts/order.const.js
Labels: Improve UI, Improve Logic

#98 BDS-70 Get export information by id
  backend/README.md
  backend/controllers/exportInfoController.js
  backend/controllers/vehicleController.js
  backend/routes/exportInfoRoutes.js
  backend/server.js
Labels: Feature

#99 [API] Get available order for vehicle
  backend/controllers/vehicleController.js
  backend/models/Delivery.js
  backend/routes/vehicleRoutes.js
Labels: Feature

#104 [API] Get available orders for vehicle
  backend/controllers/vehicleController.js
  backend/models/Delivery.js
  backend/routes/vehicleRoutes.js
Labels: Feature

#101 Feature: Handle action when click 'Complete export order'
  frontend/src/features/delivery/deliverySlice.js
  frontend/src/features/delivery/deliveryThunk.js
  frontend/src/pages/LoadOrderToTruck/index.js
  frontend/src/services/delivery.service.js
Labels: Feature

#106 Refactor project structure with docker-compose
  azure-devops/bds-build-steps.yaml
  azure-devops/bds-deploy-steps.yaml
  azure-devops/copy-env.sh
  azure-devops/healthcheck.sh
  azure-devops/rm-healthcheck.sh
  azure-devops/rm-old-be-container.sh
  azure-devops/rm-old-dev-fe-container.sh
  azure-devops/rm-old-fe-container.sh
  azure-devops/rm-old-prod-fe-container.sh
  azure-pipelines.yml
  backend/config/.env.json
  backend/server.js
  config-dev.json
  config-live.json
  docker-compose.yaml
  down.sh
  frontend/public/index.html
  frontend/src/config/.env.json
  frontend/src/index.js
  frontend/src/services/axios.js
  generate.sh
  init.sh
  master-dev-pipeline.yml
  pull.sh
  up.sh
  update.sh
Labels: Feature

#105 Feature: Filter vehicle in export order page by choosing route
  frontend/src/features/delivery/deliverySlice.js
  frontend/src/features/delivery/deliveryThunk.js
  frontend/src/pages/ExportOrder/index.js
  frontend/src/services/delivery.service.js
Labels: Feature

#107 Feature: Import order to stock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ImportOrder/index.js
  frontend/src/components/ImportOrder/index.scss
  frontend/src/features/stock/stockSlice.js
Labels: Improve UI
