Repository nguyenleminhquan/bk-delivery-system, pull requests merged in 2023-07, with the labels that each got.

#110 Feature: New shipping fee formula update
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/CreateOrder/index.js
  frontend/src/utils/consts/order.const.js
  frontend/src/utils/enums/order.enum.js
Labels: Feature, Improve Logic

#113 Update order status after deleting from vehicle
  backend/controllers/vehicleController.js
Labels: Bug

#115 Get order in stock with `import` status
  backend/controllers/stockController.js
Labels: Bug

#117 Bugfix: Re-add quantity field in create order form
  frontend/src/components/SelectOption/index.js
  frontend/src/pages/CreateOrder/CreateOrder.module.scss
  frontend/src/pages/CreateOrder/index.js
Labels: Improve Logic

#118 Feature: User must save address info before using services
  frontend/src/components/AddressForm/index.js
  frontend/src/components/AddressTab/index.js
  frontend/src/components/GeneralConfirm/GeneralConfirm.module.scss
  frontend/src/pages/Profile/index.js
  frontend/src/pages/Roles/Sender/SenderHome/index.js
Labels: Feature

#121 Feature: Vehicle management
  frontend/src/components/GeneralConfirm/index.js
  frontend/src/features/delivery/deliverySlice.js
  frontend/src/features/delivery/deliveryThunk.js
  frontend/src/pages/Authorize.js
  frontend/src/pages/Roles/Admin/AdminVehicleManagement/index.js
  frontend/src/pages/Roles/Admin/AdminVehicleManagement/index.scss
  frontend/src/services/delivery.service.js
  frontend/src/utils/constants.js
  frontend/src/utils/consts/index.js
  frontend/src/utils/consts/vehicle.const.js
  frontend/src/utils/enums/index.js
  frontend/src/utils/enums/vehicle.enum.js
Labels: Feature

#122 Thêm utils về Order (lấy area code, district code từ `address`)
  backend/resources/area-codes.js
  backend/resources/province-depth-1.json
  backend/resources/province-depth-2.json
  backend/utils/domain-utils.js
  backend/utils/order-utils.js
Labels: Feature

#124 [API] Get all vehicle at region using `/stock` instead of `/veh…
  backend/README.md
  backend/controllers/stockController.js
  backend/models/Stock.js
  backend/routes/stockRoutes.js
  backend/routes/vehicleRoutes.js
Labels: Feature, Improve Logic

#126 Use base route `/stock` instead of `/vehicle` for get available orders for vehicle at one stock
  backend/README.md
  backend/controllers/orderController.js
  backend/controllers/stockController.js
  backend/models/Vehicle.js
  backend/routes/stockRoutes.js
  backend/routes/vehicleRoutes.js
  backend/utils/order-utils.js
Labels: Feature, Improve Logic

#127 [API] Adjust push order to vehicle
  backend/README.md
  backend/controllers/vehicleController.js
Labels: Improve Logic

#128 [API] Import order to destination stock
  backend/README.md
  backend/controllers/stockController.js
  backend/models/Order.js
Labels: Feature

#129 [API] Filter available orders to import to stock according stoc…
  backend/README.md
  backend/controllers/vehicleController.js
  backend/routes/vehicleRoutes.js
Labels: Feature

#136 Can not get orders on vehicle at sender stock
  backend/controllers/stockController.js
  backend/controllers/userController.js
  backend/controllers/vehicleController.js
Labels: Bug
