Repository nguyenleminhquan/bk-delivery-system, pull requests merged in 2023-08, with the labels that each got.

#139 Delete orders on inner vehicle when importing orders to stock
  backend/controllers/stockController.js
Labels: Bug

#141 Return detail orders when using import order
  backend/controllers/stockController.js
  backend/models/ImportInfo.js
Labels: Improve Logic

#142 Fix: Import orders UI bugs
  frontend/src/components/VehicleManagementUpsert/index.js
  frontend/src/features/stock/stockSlice.js
  frontend/src/pages/LoadOrderToTruck/index.js
Labels: Bug

#143 Fix: stopPropagation for delete button in confirm vehicle order popup
  frontend/src/features/stock/stockSlice.js
  frontend/src/pages/LoadOrderToTruck/index.js
Labels: Bug

#144 Implement finding the best way between multiple points
  backend/README.md
  backend/config/db/connectDB.js
  backend/controllers/mapsController.js
  backend/models/Vehicle.js
  backend/routes/mapRoutes.js
  backend/routes/vehicleRoutes.js
  backend/server.js
  backend/utils/maps-utils.js
Labels: Feature

#146 Fix: Fill up data for employee data upsert and fix bug cannot edit employee info
  backend/controllers/userController.js
  frontend/src/components/EmployeeUpsert/index.js
  frontend/src/pages/Roles/Admin/AdminEmployeeManagement/index.js
Labels: Bug

#147 Không thấy đơn hàng ở trong kho avail cho xe tải sau khi xoá đơn hàng khỏi xe tải
  backend/README.md
  backend/controllers/vehicleController.js
Labels: Bug

#148 Fix: Remove password in edit-employee payload
  frontend/src/components/EmployeeUpsert/index.js
Labels: Bug

#149 Fix: Cannot create new employee
  frontend/src/components/EmployeeUpsert/index.js
Labels: Bug
