Repository nguyenleminhquan/bk-delivery-system, pull requests merged in 2023-09, with the labels that each got.

#151 Cannot use get API get available order for vehicle at destination stock
  backend/controllers/stockController.js
  backend/utils/order-utils.js
Labels: Bug

#152 Can not use get avail order for vehicle at destination stock
  backend/controllers/vehicleController.js
  backend/models/Order.js
Labels: Bug

#156 Fix: refresh vehicle status, avail list after CRUD order
  frontend/src/features/delivery/deliverySlice.js
  frontend/src/pages/LoadOrderToTruck/index.js
Labels: Bug, Improve UI

#157 Fix: add stock_id to payload of export-order api
  frontend/src/pages/LoadOrderToTruck/index.js
  frontend/src/services/delivery.service.js
Labels: Bug

#158 Feature: Responsive system
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/AddressForm/AddressForm.module.scss
  frontend/src/components/AddressForm/index.js
  frontend/src/components/AddressTab/index.js
  frontend/src/components/BankAccountTab/index.js
  frontend/src/components/ChangePassTab/index.js
  frontend/src/components/ConfirmPopup/ConfirmPopup.module.scss
  frontend/src/components/GeneralConfirm/GeneralConfirm.module.scss
  frontend/src/components/ImportOrder/index.js
  frontend/src/components/PersonalTab/index.js
  frontend/src/components/Sidebar/Sidebar.module.scss
  frontend/src/components/Sidebar/index.js
  frontend/src/components/Sidebar/index.scss
  frontend/src/components/StockerHeader/index.js
  frontend/src/components/StockerHeader/index.scss
  frontend/src/components/SupportRequest/index.js
  frontend/src/components/SupportRequest/index.scss
  frontend/src/components/Table/index.js
  frontend/src/components/Table/index.scss
  frontend/src/components/Tabs/index.js
  frontend/src/components/Tabs/index.scss
  frontend/src/components/VehicleBoard/index.js
  frontend/src/components/VehicleBoard/index.scss
  frontend/src/features/user/userSlice.js
  frontend/src/index.js
  frontend/src/pages/CreateOrder/CreateOrder.module.scss
  frontend/src/pages/CreateOrder/index.js
  frontend/src/pages/ExportOrder/index.js
  frontend/src/pages/LoadOrderToTruck/LoadOrderToTruck.module.scss
  frontend/src/pages/LoadOrderToTruck/index.js
  frontend/src/pages/Profile/index.js
  frontend/src/pages/Profile/index.scss
  frontend/src/pages/Roles/Admin/AdminEmployeeManagement/index.js
  frontend/src/pages/Roles/Admin/AdminHome/index.js
  frontend/src/pages/Roles/Admin/AdminOrderManagement/index.js
  frontend/src/pages/Roles/Admin/AdminOrderManagement/index.scss
  frontend/src/pages/Roles/Admin/AdminStockManagement/index.js
  frontend/src/pages/Roles/Admin/AdminVehicleManagement/index.js
  frontend/src/pages/Roles/Driver/DriverHistory/index.js
  frontend/src/pages/Roles/Driver/DriverHome/index.js
  frontend/src/pages/Roles/Driver/DriverHome/index.scss
  frontend/src/pages/Roles/Sender/SenderHome/Sender.module.scss
  frontend/src/pages/Roles/Sender/SenderHome/index.js
  frontend/src/pages/Roles/Stocker/ImportExportHistory/index.js
  frontend/src/styles/_breakpoints.scss
  frontend/src/styles/styles.scss
Labels: Improve UI, Responsive

#161 Sắp xếp order theo stock khi xuất kho
  backend/controllers/deliveryController.js
  backend/controllers/exportInfoController.js
  backend/controllers/stockController.js
  backend/controllers/vehicleController.js
  backend/models/ExportInfo.js
Labels: Feature, Improve Logic

#166 Can import order to stock using license plate number
  backend/controllers/vehicleController.js
Labels: Feature

#168 Fix: System bugs
  frontend/src/components/ConfirmPopup/ConfirmPopup.module.scss
  frontend/src/components/GeneralConfirm/GeneralConfirm.module.scss
  frontend/src/components/ImportOrder/index.js
  frontend/src/components/Sidebar/index.js
  frontend/src/features/user/orderSlice.js
  frontend/src/features/user/orderThunk.js
  frontend/src/pages/Roles/Sender/SenderHome/index.js
  frontend/src/services/order.service.js
Labels: Bug

#170 Fix: Improve UI
  frontend/src/components/BankAccountTab/index.js
  frontend/src/components/ChangePassTab/index.js
  frontend/src/components/PersonalTab/index.js
  frontend/src/components/Sidebar/index.js
  frontend/src/features/delivery/deliverySlice.js
  frontend/src/features/user/orderSlice.js
  frontend/src/features/user/userSlice.js
  frontend/src/pages/ExportOrder/index.js
  frontend/src/utils/constants.js
Labels: Bug, Improve UI

#171 Can't import order to stock using license plate number
  backend/controllers/stockController.js
Labels: Bug
